# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf3b4f94472840ae06787a756bab1aa1cd1b45d394bccbed24fc337ad4b39cf9ac01088483c99b204bc40cc1a74bd052c5a3f9f7e6973e5c94e7c30f2cdfa04c

test:
  secret_key_base: 21148d4d2a33d6cf212322a62ad7a5b5f29f223d929e007af14f0d3eed06a6c22150d6f5068c891fec7e1aee88d3f6985c622aadcdd8db896d227bde4cf198b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: fbdd492e81caad39d3e5d5aa4f8763e3e67cf47188c3b52e4fdb3c2f46148dda9426d5e1170d3aad3e01d8374af2805c453b579aa1f9825a7270bc20bbeb1111